// import '../style/index.css'

const Description = () =>{
  return (
    <p className='text-bluegray-900'>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse maximus eu risus nec finibus. Quisque nisi magna, tincidunt eget est sed, mattis blandit nunc. In mauris elit, feugiat nec eros eu, commodo eleifend nunc. Phasellus sit amet suscipit massa, ac molestie turpis. Praesent eleifend orci dolor, et dapibus lorem ornare eget. Cras pharetra efficitur lacus eget euismod. Suspendisse tempus sit amet nulla tincidunt fringilla. Duis semper aliquet urna vel iaculis. Proin dictum sapien vitae velit mollis, nec laoreet neque vulputate. Praesent justo mi, lacinia eget faucibus id, scelerisque eget lectus. Aenean odio ante, blandit nec auctor pretium, consectetur in justo. Vestibulum quis suscipit quam. Aenean pretium a orci eu blandit. Nulla tempor nunc dapibus lorem venenatis suscipit. Curabitur imperdiet nibh at malesuada maximus. Proin id vehicula odio.

      Vivamus tortor diam, viverra eu nunc non, suscipit rutrum turpis. Praesent condimentum turpis sollicitudin lectus tempor tempor. Curabitur sed condimentum magna. Maecenas tellus velit, dignissim iaculis quam quis, fringilla viverra enim. Nullam elementum tellus odio, at varius metus placerat in. Sed sagittis ultrices molestie. Aenean interdum sollicitudin neque eget cursus. Pellentesque vehicula velit vel risus sollicitudin auctor. Quisque aliquet blandit libero, ac iaculis orci dictum ultrices.

      Donec finibus vulputate erat, lacinia gravida nibh. Vivamus sed dignissim sapien, sit amet ornare mauris. Sed non elit at tortor dignissim consectetur. Suspendisse mauris mauris, venenatis vel sagittis ac, mollis a sapien. Vivamus elementum lorem nulla, non tincidunt elit scelerisque a. Mauris ante justo, pellentesque sed nisl sit amet, tincidunt bibendum lectus. Nam gravida ultricies tortor a eleifend. Maecenas sed euismod nibh, eu euismod sem. Etiam congue eget ante feugiat semper. Duis eu finibus elit, in auctor ligula. Pellentesque vehicula, augue posuere imperdiet fringilla, mauris dui imperdiet turpis, vel auctor metus elit ac ex.

      Morbi ipsum tellus, rhoncus ac malesuada a, fermentum et velit. Nunc consequat enim nisi, interdum scelerisque purus venenatis vel. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed justo ipsum, iaculis quis gravida eu, porta sit amet nibh. Aliquam erat volutpat. Sed tempor nunc nec urna fermentum, sed imperdiet arcu aliquet. Donec tincidunt, felis nec sollicitudin cursus, orci dolor lobortis nulla, vel tempus risus ligula vehicula ante. In ullamcorper fermentum sapien at dictum. Vestibulum libero sapien, lacinia non nulla dignissim, commodo iaculis nulla. Mauris pharetra ullamcorper diam, eget consequat quam convallis ac.

      Phasellus in ex in est laoreet pretium. Aenean id urna et tortor malesuada fermentum. Vivamus auctor augue tortor, nec blandit lectus lacinia vitae. Aliquam elementum, enim eget lacinia ullamcorper, tortor libero dapibus dolor, sed efficitur leo nisi nec lorem. Curabitur commodo hendrerit enim. Donec vitae lacus at tortor rutrum condimentum. Nam bibendum magna enim, ac varius ligula aliquet vitae. Pellentesque vitae libero tristique, egestas sem eu, eleifend turpis. Nam eu risus neque. Nam enim erat, interdum id eros vitae, pulvinar pellentesque sem. Donec eu congue tortor, et pharetra nunc. Integer suscipit tempor odio, nec fringilla augue congue vel. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
    </p>
  )
}

export default Description;